/* run.config
   DONTRUN:
   LOG: @PTEST_NAME@.labels
   LOG: @PTEST_NAME@.hyperlabels
   LOG: @PTEST_NAME@.log
   EXEC: rm -f @PTEST_DIR@/result/@PTEST_NAME@.*
   EXEC: cp @PTEST_DIR@/quandrant_bindings.hyperlabels @PTEST_DIR@/result/@PTEST_NAME@.hyperlabels
   EXECNOW: @frama-c@ -luncov-share ./share -luncov-wp @PTEST_DIR@/@PTEST_NAME@.c -luncov-no-show-time -luncov-hyperlabels @PTEST_DIR@/result/@PTEST_NAME@.hyperlabels -wp-msg-key no-time-info -luncov-labels @PTEST_DIR@/result/@PTEST_NAME@.labels > @PTEST_DIR@/result/@PTEST_NAME@.log
   OPT:
*/

/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int quadrant(int x1, int y1, int x2, int y2)
 {
   int __retres;
   pc_label_bindings(x1 >= 0 && ((x2 >= 0 && y1 >= 0) && y2 >= 0),1,"CACC",1,
                     1,"pa",((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(! (x1 >= 0) && ((x2 >= 0 && y1 >= 0) && y2 >= 0),2,
                     "CACC",1,1,"pb",
                     ((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(x2 >= 0 && ((x1 >= 0 && y1 >= 0) && y2 >= 0),3,"CACC",2,
                     1,"pa",((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(! (x2 >= 0) && ((x1 >= 0 && y1 >= 0) && y2 >= 0),4,
                     "CACC",2,1,"pb",
                     ((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(y1 >= 0 && ((x1 >= 0 && x2 >= 0) && y2 >= 0),5,"CACC",3,
                     1,"pa",((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(! (y1 >= 0) && ((x1 >= 0 && x2 >= 0) && y2 >= 0),6,
                     "CACC",3,1,"pb",
                     ((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(y2 >= 0 && ((x1 >= 0 && x2 >= 0) && y1 >= 0),7,"CACC",4,
                     1,"pa",((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(! (y2 >= 0) && ((x1 >= 0 && x2 >= 0) && y1 >= 0),8,
                     "CACC",4,1,"pb",
                     ((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(x1 >= 0 && ((x2 >= 0 && y1 >= 0) && y2 >= 0),33,"RACC",
                     17,3,"cA1",x2 >= 0,"cA2",y1 >= 0,"cA3",y2 >= 0);
   pc_label_bindings(! (x1 >= 0) && ((x2 >= 0 && y1 >= 0) && y2 >= 0),34,
                     "RACC",17,3,"cB1",x2 >= 0,"cB2",y1 >= 0,"cB3",y2 >= 0);
   pc_label_bindings(x2 >= 0 && ((x1 >= 0 && y1 >= 0) && y2 >= 0),35,"RACC",
                     18,3,"cA1",x1 >= 0,"cA2",y1 >= 0,"cA3",y2 >= 0);
   pc_label_bindings(! (x2 >= 0) && ((x1 >= 0 && y1 >= 0) && y2 >= 0),36,
                     "RACC",18,3,"cB1",x1 >= 0,"cB2",y1 >= 0,"cB3",y2 >= 0);
   pc_label_bindings(y1 >= 0 && ((x1 >= 0 && x2 >= 0) && y2 >= 0),37,"RACC",
                     19,3,"cA1",x1 >= 0,"cA2",x2 >= 0,"cA3",y2 >= 0);
   pc_label_bindings(! (y1 >= 0) && ((x1 >= 0 && x2 >= 0) && y2 >= 0),38,
                     "RACC",19,3,"cB1",x1 >= 0,"cB2",x2 >= 0,"cB3",y2 >= 0);
   pc_label_bindings(y2 >= 0 && ((x1 >= 0 && x2 >= 0) && y1 >= 0),39,"RACC",
                     20,3,"cA1",x1 >= 0,"cA2",x2 >= 0,"cA3",y1 >= 0);
   pc_label_bindings(! (y2 >= 0) && ((x1 >= 0 && x2 >= 0) && y1 >= 0),40,
                     "RACC",20,3,"cB1",x1 >= 0,"cB2",x2 >= 0,"cB3",y1 >= 0);
   if (((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0) {
     __retres = 1;
     goto return_label;
   }
   pc_label_bindings(x1 <= 0 && ((x2 <= 0 && y1 >= 0) && y2 >= 0),9,"CACC",5,
                     1,"pa",((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(! (x1 <= 0) && ((x2 <= 0 && y1 >= 0) && y2 >= 0),10,
                     "CACC",5,1,"pb",
                     ((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(x2 <= 0 && ((x1 <= 0 && y1 >= 0) && y2 >= 0),11,"CACC",
                     6,1,"pa",((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(! (x2 <= 0) && ((x1 <= 0 && y1 >= 0) && y2 >= 0),12,
                     "CACC",6,1,"pb",
                     ((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(y1 >= 0 && ((x1 <= 0 && x2 <= 0) && y2 >= 0),13,"CACC",
                     7,1,"pa",((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(! (y1 >= 0) && ((x1 <= 0 && x2 <= 0) && y2 >= 0),14,
                     "CACC",7,1,"pb",
                     ((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(y2 >= 0 && ((x1 <= 0 && x2 <= 0) && y1 >= 0),15,"CACC",
                     8,1,"pa",((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(! (y2 >= 0) && ((x1 <= 0 && x2 <= 0) && y1 >= 0),16,
                     "CACC",8,1,"pb",
                     ((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0);
   pc_label_bindings(x1 <= 0 && ((x2 <= 0 && y1 >= 0) && y2 >= 0),41,"RACC",
                     21,3,"cA1",x2 <= 0,"cA2",y1 >= 0,"cA3",y2 >= 0);
   pc_label_bindings(! (x1 <= 0) && ((x2 <= 0 && y1 >= 0) && y2 >= 0),42,
                     "RACC",21,3,"cB1",x2 <= 0,"cB2",y1 >= 0,"cB3",y2 >= 0);
   pc_label_bindings(x2 <= 0 && ((x1 <= 0 && y1 >= 0) && y2 >= 0),43,"RACC",
                     22,3,"cA1",x1 <= 0,"cA2",y1 >= 0,"cA3",y2 >= 0);
   pc_label_bindings(! (x2 <= 0) && ((x1 <= 0 && y1 >= 0) && y2 >= 0),44,
                     "RACC",22,3,"cB1",x1 <= 0,"cB2",y1 >= 0,"cB3",y2 >= 0);
   pc_label_bindings(y1 >= 0 && ((x1 <= 0 && x2 <= 0) && y2 >= 0),45,"RACC",
                     23,3,"cA1",x1 <= 0,"cA2",x2 <= 0,"cA3",y2 >= 0);
   pc_label_bindings(! (y1 >= 0) && ((x1 <= 0 && x2 <= 0) && y2 >= 0),46,
                     "RACC",23,3,"cB1",x1 <= 0,"cB2",x2 <= 0,"cB3",y2 >= 0);
   pc_label_bindings(y2 >= 0 && ((x1 <= 0 && x2 <= 0) && y1 >= 0),47,"RACC",
                     24,3,"cA1",x1 <= 0,"cA2",x2 <= 0,"cA3",y1 >= 0);
   pc_label_bindings(! (y2 >= 0) && ((x1 <= 0 && x2 <= 0) && y1 >= 0),48,
                     "RACC",24,3,"cB1",x1 <= 0,"cB2",x2 <= 0,"cB3",y1 >= 0);
   if (((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0) {
     __retres = 2;
     goto return_label;
   }
   pc_label_bindings(x1 <= 0 && ((x2 <= 0 && y1 <= 0) && y2 <= 0),17,"CACC",
                     9,1,"pa",((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(! (x1 <= 0) && ((x2 <= 0 && y1 <= 0) && y2 <= 0),18,
                     "CACC",9,1,"pb",
                     ((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(x2 <= 0 && ((x1 <= 0 && y1 <= 0) && y2 <= 0),19,"CACC",
                     10,1,"pa",((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(! (x2 <= 0) && ((x1 <= 0 && y1 <= 0) && y2 <= 0),20,
                     "CACC",10,1,"pb",
                     ((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(y1 <= 0 && ((x1 <= 0 && x2 <= 0) && y2 <= 0),21,"CACC",
                     11,1,"pa",((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(! (y1 <= 0) && ((x1 <= 0 && x2 <= 0) && y2 <= 0),22,
                     "CACC",11,1,"pb",
                     ((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(y2 <= 0 && ((x1 <= 0 && x2 <= 0) && y1 <= 0),23,"CACC",
                     12,1,"pa",((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(! (y2 <= 0) && ((x1 <= 0 && x2 <= 0) && y1 <= 0),24,
                     "CACC",12,1,"pb",
                     ((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(x1 <= 0 && ((x2 <= 0 && y1 <= 0) && y2 <= 0),49,"RACC",
                     25,3,"cA1",x2 <= 0,"cA2",y1 <= 0,"cA3",y2 <= 0);
   pc_label_bindings(! (x1 <= 0) && ((x2 <= 0 && y1 <= 0) && y2 <= 0),50,
                     "RACC",25,3,"cB1",x2 <= 0,"cB2",y1 <= 0,"cB3",y2 <= 0);
   pc_label_bindings(x2 <= 0 && ((x1 <= 0 && y1 <= 0) && y2 <= 0),51,"RACC",
                     26,3,"cA1",x1 <= 0,"cA2",y1 <= 0,"cA3",y2 <= 0);
   pc_label_bindings(! (x2 <= 0) && ((x1 <= 0 && y1 <= 0) && y2 <= 0),52,
                     "RACC",26,3,"cB1",x1 <= 0,"cB2",y1 <= 0,"cB3",y2 <= 0);
   pc_label_bindings(y1 <= 0 && ((x1 <= 0 && x2 <= 0) && y2 <= 0),53,"RACC",
                     27,3,"cA1",x1 <= 0,"cA2",x2 <= 0,"cA3",y2 <= 0);
   pc_label_bindings(! (y1 <= 0) && ((x1 <= 0 && x2 <= 0) && y2 <= 0),54,
                     "RACC",27,3,"cB1",x1 <= 0,"cB2",x2 <= 0,"cB3",y2 <= 0);
   pc_label_bindings(y2 <= 0 && ((x1 <= 0 && x2 <= 0) && y1 <= 0),55,"RACC",
                     28,3,"cA1",x1 <= 0,"cA2",x2 <= 0,"cA3",y1 <= 0);
   pc_label_bindings(! (y2 <= 0) && ((x1 <= 0 && x2 <= 0) && y1 <= 0),56,
                     "RACC",28,3,"cB1",x1 <= 0,"cB2",x2 <= 0,"cB3",y1 <= 0);
   if (((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0) {
     __retres = 3;
     goto return_label;
   }
   pc_label_bindings(x1 >= 0 && ((x2 >= 0 && y1 <= 0) && y2 <= 0),25,"CACC",
                     13,1,"pa",((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(! (x1 >= 0) && ((x2 >= 0 && y1 <= 0) && y2 <= 0),26,
                     "CACC",13,1,"pb",
                     ((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(x2 >= 0 && ((x1 >= 0 && y1 <= 0) && y2 <= 0),27,"CACC",
                     14,1,"pa",((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(! (x2 >= 0) && ((x1 >= 0 && y1 <= 0) && y2 <= 0),28,
                     "CACC",14,1,"pb",
                     ((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(y1 <= 0 && ((x1 >= 0 && x2 >= 0) && y2 <= 0),29,"CACC",
                     15,1,"pa",((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(! (y1 <= 0) && ((x1 >= 0 && x2 >= 0) && y2 <= 0),30,
                     "CACC",15,1,"pb",
                     ((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(y2 <= 0 && ((x1 >= 0 && x2 >= 0) && y1 <= 0),31,"CACC",
                     16,1,"pa",((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(! (y2 <= 0) && ((x1 >= 0 && x2 >= 0) && y1 <= 0),32,
                     "CACC",16,1,"pb",
                     ((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0);
   pc_label_bindings(x1 >= 0 && ((x2 >= 0 && y1 <= 0) && y2 <= 0),57,"RACC",
                     29,3,"cA1",x2 >= 0,"cA2",y1 <= 0,"cA3",y2 <= 0);
   pc_label_bindings(! (x1 >= 0) && ((x2 >= 0 && y1 <= 0) && y2 <= 0),58,
                     "RACC",29,3,"cB1",x2 >= 0,"cB2",y1 <= 0,"cB3",y2 <= 0);
   pc_label_bindings(x2 >= 0 && ((x1 >= 0 && y1 <= 0) && y2 <= 0),59,"RACC",
                     30,3,"cA1",x1 >= 0,"cA2",y1 <= 0,"cA3",y2 <= 0);
   pc_label_bindings(! (x2 >= 0) && ((x1 >= 0 && y1 <= 0) && y2 <= 0),60,
                     "RACC",30,3,"cB1",x1 >= 0,"cB2",y1 <= 0,"cB3",y2 <= 0);
   pc_label_bindings(y1 <= 0 && ((x1 >= 0 && x2 >= 0) && y2 <= 0),61,"RACC",
                     31,3,"cA1",x1 >= 0,"cA2",x2 >= 0,"cA3",y2 <= 0);
   pc_label_bindings(! (y1 <= 0) && ((x1 >= 0 && x2 >= 0) && y2 <= 0),62,
                     "RACC",31,3,"cB1",x1 >= 0,"cB2",x2 >= 0,"cB3",y2 <= 0);
   pc_label_bindings(y2 <= 0 && ((x1 >= 0 && x2 >= 0) && y1 <= 0),63,"RACC",
                     32,3,"cA1",x1 >= 0,"cA2",x2 >= 0,"cA3",y1 <= 0);
   pc_label_bindings(! (y2 <= 0) && ((x1 >= 0 && x2 >= 0) && y1 <= 0),64,
                     "RACC",32,3,"cB1",x1 >= 0,"cB2",x2 >= 0,"cB3",y1 <= 0);
   if (((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0) {
     __retres = 4;
     goto return_label;
   }
   __retres = 0;
   return_label: return __retres;
 }

int main(){
    
    quadrant(1,2,3,4);
    quadrant(4,3,2,1);
    quadrant(1,3,4,2);
    quadrant(4,1,2,3);
    quadrant(-1,2,3,4);
    quadrant(4,-3,2,1);
    quadrant(1,3,-4,2);
    quadrant(4,1,2,-3);
    quadrant(1,2,-3,4);
    quadrant(4,-3,2,1);
    quadrant(-1,3,4,2);
    quadrant(4,-1,2,-3);
    return 0;
}

