/* run.config
   STDOPT: +"-luncov-wp -wp-prover qed -wp-msg-key no-time-info"
*/




/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int quadrant(int x1, int y1, int x2, int y2)
 {
   int __retres;
   pc_label(x1 >= 0 && (x2 >= 0 && (y1 >= 0 && y2 >= 0)),1,"MCC");
   pc_label(x1 >= 0 && (x2 >= 0 && (y1 >= 0 && ! (y2 >= 0))),2,"MCC");
   pc_label(x1 >= 0 && (x2 >= 0 && (! (y1 >= 0) && y2 >= 0)),3,"MCC");
   pc_label(x1 >= 0 && (x2 >= 0 && (! (y1 >= 0) && ! (y2 >= 0))),4,"MCC");
   pc_label(x1 >= 0 && (! (x2 >= 0) && (y1 >= 0 && y2 >= 0)),5,"MCC");
   pc_label(x1 >= 0 && (! (x2 >= 0) && (y1 >= 0 && ! (y2 >= 0))),6,"MCC");
   pc_label(x1 >= 0 && (! (x2 >= 0) && (! (y1 >= 0) && y2 >= 0)),7,"MCC");
   pc_label(x1 >= 0 && (! (x2 >= 0) && (! (y1 >= 0) && ! (y2 >= 0))),8,"MCC");
   pc_label(! (x1 >= 0) && (x2 >= 0 && (y1 >= 0 && y2 >= 0)),9,"MCC");
   pc_label(! (x1 >= 0) && (x2 >= 0 && (y1 >= 0 && ! (y2 >= 0))),10,"MCC");
   pc_label(! (x1 >= 0) && (x2 >= 0 && (! (y1 >= 0) && y2 >= 0)),11,"MCC");
   pc_label(! (x1 >= 0) && (x2 >= 0 && (! (y1 >= 0) && ! (y2 >= 0))),12,
            "MCC");
   pc_label(! (x1 >= 0) && (! (x2 >= 0) && (y1 >= 0 && y2 >= 0)),13,"MCC");
   pc_label(! (x1 >= 0) && (! (x2 >= 0) && (y1 >= 0 && ! (y2 >= 0))),14,
            "MCC");
   pc_label(! (x1 >= 0) && (! (x2 >= 0) && (! (y1 >= 0) && y2 >= 0)),15,
            "MCC");
   pc_label(! (x1 >= 0) && (! (x2 >= 0) && (! (y1 >= 0) && ! (y2 >= 0))),16,
            "MCC");
   if (((x1 >= 0 && x2 >= 0) && y1 >= 0) && y2 >= 0) {
     __retres = 1;
     goto return_label;
   }
   pc_label(x1 <= 0 && (x2 <= 0 && (y1 >= 0 && y2 >= 0)),17,"MCC");
   pc_label(x1 <= 0 && (x2 <= 0 && (y1 >= 0 && ! (y2 >= 0))),18,"MCC");
   pc_label(x1 <= 0 && (x2 <= 0 && (! (y1 >= 0) && y2 >= 0)),19,"MCC");
   pc_label(x1 <= 0 && (x2 <= 0 && (! (y1 >= 0) && ! (y2 >= 0))),20,"MCC");
   pc_label(x1 <= 0 && (! (x2 <= 0) && (y1 >= 0 && y2 >= 0)),21,"MCC");
   pc_label(x1 <= 0 && (! (x2 <= 0) && (y1 >= 0 && ! (y2 >= 0))),22,"MCC");
   pc_label(x1 <= 0 && (! (x2 <= 0) && (! (y1 >= 0) && y2 >= 0)),23,"MCC");
   pc_label(x1 <= 0 && (! (x2 <= 0) && (! (y1 >= 0) && ! (y2 >= 0))),24,
            "MCC");
   pc_label(! (x1 <= 0) && (x2 <= 0 && (y1 >= 0 && y2 >= 0)),25,"MCC");
   pc_label(! (x1 <= 0) && (x2 <= 0 && (y1 >= 0 && ! (y2 >= 0))),26,"MCC");
   pc_label(! (x1 <= 0) && (x2 <= 0 && (! (y1 >= 0) && y2 >= 0)),27,"MCC");
   pc_label(! (x1 <= 0) && (x2 <= 0 && (! (y1 >= 0) && ! (y2 >= 0))),28,
            "MCC");
   pc_label(! (x1 <= 0) && (! (x2 <= 0) && (y1 >= 0 && y2 >= 0)),29,"MCC");
   pc_label(! (x1 <= 0) && (! (x2 <= 0) && (y1 >= 0 && ! (y2 >= 0))),30,
            "MCC");
   pc_label(! (x1 <= 0) && (! (x2 <= 0) && (! (y1 >= 0) && y2 >= 0)),31,
            "MCC");
   pc_label(! (x1 <= 0) && (! (x2 <= 0) && (! (y1 >= 0) && ! (y2 >= 0))),32,
            "MCC");
   if (((x1 <= 0 && x2 <= 0) && y1 >= 0) && y2 >= 0) {
     __retres = 2;
     goto return_label;
   }
   pc_label(x1 <= 0 && (x2 <= 0 && (y1 <= 0 && y2 <= 0)),33,"MCC");
   pc_label(x1 <= 0 && (x2 <= 0 && (y1 <= 0 && ! (y2 <= 0))),34,"MCC");
   pc_label(x1 <= 0 && (x2 <= 0 && (! (y1 <= 0) && y2 <= 0)),35,"MCC");
   pc_label(x1 <= 0 && (x2 <= 0 && (! (y1 <= 0) && ! (y2 <= 0))),36,"MCC");
   pc_label(x1 <= 0 && (! (x2 <= 0) && (y1 <= 0 && y2 <= 0)),37,"MCC");
   pc_label(x1 <= 0 && (! (x2 <= 0) && (y1 <= 0 && ! (y2 <= 0))),38,"MCC");
   pc_label(x1 <= 0 && (! (x2 <= 0) && (! (y1 <= 0) && y2 <= 0)),39,"MCC");
   pc_label(x1 <= 0 && (! (x2 <= 0) && (! (y1 <= 0) && ! (y2 <= 0))),40,
            "MCC");
   pc_label(! (x1 <= 0) && (x2 <= 0 && (y1 <= 0 && y2 <= 0)),41,"MCC");
   pc_label(! (x1 <= 0) && (x2 <= 0 && (y1 <= 0 && ! (y2 <= 0))),42,"MCC");
   pc_label(! (x1 <= 0) && (x2 <= 0 && (! (y1 <= 0) && y2 <= 0)),43,"MCC");
   pc_label(! (x1 <= 0) && (x2 <= 0 && (! (y1 <= 0) && ! (y2 <= 0))),44,
            "MCC");
   pc_label(! (x1 <= 0) && (! (x2 <= 0) && (y1 <= 0 && y2 <= 0)),45,"MCC");
   pc_label(! (x1 <= 0) && (! (x2 <= 0) && (y1 <= 0 && ! (y2 <= 0))),46,
            "MCC");
   pc_label(! (x1 <= 0) && (! (x2 <= 0) && (! (y1 <= 0) && y2 <= 0)),47,
            "MCC");
   pc_label(! (x1 <= 0) && (! (x2 <= 0) && (! (y1 <= 0) && ! (y2 <= 0))),48,
            "MCC");
   if (((x1 <= 0 && x2 <= 0) && y1 <= 0) && y2 <= 0) {
     __retres = 3;
     goto return_label;
   }
   pc_label(x1 >= 0 && (x2 >= 0 && (y1 <= 0 && y2 <= 0)),49,"MCC");
   pc_label(x1 >= 0 && (x2 >= 0 && (y1 <= 0 && ! (y2 <= 0))),50,"MCC");
   pc_label(x1 >= 0 && (x2 >= 0 && (! (y1 <= 0) && y2 <= 0)),51,"MCC");
   pc_label(x1 >= 0 && (x2 >= 0 && (! (y1 <= 0) && ! (y2 <= 0))),52,"MCC");
   pc_label(x1 >= 0 && (! (x2 >= 0) && (y1 <= 0 && y2 <= 0)),53,"MCC");
   pc_label(x1 >= 0 && (! (x2 >= 0) && (y1 <= 0 && ! (y2 <= 0))),54,"MCC");
   pc_label(x1 >= 0 && (! (x2 >= 0) && (! (y1 <= 0) && y2 <= 0)),55,"MCC");
   pc_label(x1 >= 0 && (! (x2 >= 0) && (! (y1 <= 0) && ! (y2 <= 0))),56,
            "MCC");
   pc_label(! (x1 >= 0) && (x2 >= 0 && (y1 <= 0 && y2 <= 0)),57,"MCC");
   pc_label(! (x1 >= 0) && (x2 >= 0 && (y1 <= 0 && ! (y2 <= 0))),58,"MCC");
   pc_label(! (x1 >= 0) && (x2 >= 0 && (! (y1 <= 0) && y2 <= 0)),59,"MCC");
   pc_label(! (x1 >= 0) && (x2 >= 0 && (! (y1 <= 0) && ! (y2 <= 0))),60,
            "MCC");
   pc_label(! (x1 >= 0) && (! (x2 >= 0) && (y1 <= 0 && y2 <= 0)),61,"MCC");
   pc_label(! (x1 >= 0) && (! (x2 >= 0) && (y1 <= 0 && ! (y2 <= 0))),62,
            "MCC");
   pc_label(! (x1 >= 0) && (! (x2 >= 0) && (! (y1 <= 0) && y2 <= 0)),63,
            "MCC");
   pc_label(! (x1 >= 0) && (! (x2 >= 0) && (! (y1 <= 0) && ! (y2 <= 0))),64,
            "MCC");
   if (((x1 >= 0 && x2 >= 0) && y1 <= 0) && y2 <= 0) {
     __retres = 4;
     goto return_label;
   }
   __retres = 0;
   return_label: return __retres;
 }
 
int main(){
    quadrant(1,2,3,4);
    quadrant(4,3,2,1);
    quadrant(1,3,4,2);
    quadrant(4,1,2,3);
    quadrant(-1,2,3,4);
    quadrant(4,-3,2,1);
    quadrant(1,3,-4,2);
    quadrant(4,1,2,-3);
    quadrant(1,2,-3,4);
    quadrant(4,-3,2,1);
    quadrant(-1,3,4,2);
    quadrant(4,-1,2,-3);
    return 0;
}

