/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int f(void)
 {
   int __retres;
   pc_label(1,1,"STMT");
   __retres = 0;
   pc_label(1,2,"STMT");
   return __retres;
 }

int maintest(int c)
{
  int __retres;
  pc_label(1,3,"STMT");
  int a = 1;
  int b = 2;
  test: pc_label(1,4,"STMT");
  if (a) {
    pc_label(1,5,"STMT");
    if (b) {
      pc_label(1,6,"STMT");
      b = 3;
    }
    else {
      pc_label(1,7,"STMT");
      test2: {
               pc_label(1,8,"STMT");
               a = f();
             }
    }
  }
  else {
    pc_label(1,9,"STMT");
    int i = a;
    while (1) {
      pc_label(1,12,"STMT");
      if (i < b) pc_label(1,10,"STMT");
      else {
        pc_label(1,11,"STMT");
        break;
      }
      f();
      i ++;
    }
  }
  test4: pc_label(1,13,"STMT");
  switch (c) {
    int tmp;
    test5: case 1: case 14: pc_label(1,14,"STMT");
    __retres = a + b;
    pc_label(1,15,"STMT");
    goto return_label;
    case 12: case 13: pc_label(1,16,"STMT");
    __retres = c;
    pc_label(1,17,"STMT");
    goto return_label;
    default: pc_label(1,18,"STMT");
    if (c) {
      pc_label(1,19,"STMT");
      tmp = 0;
    }
    else {
      pc_label(1,20,"STMT");
      tmp = c;
    }
    __retres = tmp;
    pc_label(1,21,"STMT");
    goto return_label;
  }
  __retres = 0;
  return_label: {
                  pc_label(1,22,"STMT");
                  return __retres;
                }
}


