/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int maintest(int a, int b, int c, int d)
 {
   int __retres;
   pc_label(a <= b,1,"CC");
   pc_label(! (a <= b),2,"CC");
   pc_label(c >= b,3,"CC");
   pc_label(! (c >= b),4,"CC");
   if (a <= b && c >= b) {
     __retres = 0;
     goto return_label;
   }
   __retres = 1;
   return_label: return __retres;
 }


