/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int add(int a, int b)
 {
   int __retres;
   pc_label(1,7,"FC");
   __retres = a + b;
   return __retres;
 }

int sub(int a, int b)
{
  int __retres;
  pc_label(1,8,"FC");
  pc_label(a >= b,1,"CC");
  pc_label(! (a >= b),2,"CC");
  if (a >= b) {
    __retres = a - b;
    goto return_label;
  }
  else {
    __retres = b - a;
    goto return_label;
  }
  return_label: return __retres;
}

int mul(int a, int b)
{
  int __retres;
  __retres = a * b;
  return __retres;
}

int mod(int a, int b)
{
  int __retres;
  __retres = a % b;
  return __retres;
}

int div(int a, int b)
{
  int __retres;
  int c = mod(a,b);
  if (c) {
    __retres = a / b;
    goto return_label;
  }
  else {
    __retres = c;
    goto return_label;
  }
  return_label: return __retres;
}

int main(void)
{
  int __retres;
  int tmp_1;
  int tmp_0;
  int tmp;
  pc_label(1,9,"FC");
  int a = 24;
  int b = 42;
  pc_label(a < 0,3,"CC");
  pc_label(! (a < 0),4,"CC");
  pc_label(a > 100,5,"CC");
  pc_label(! (a > 100),6,"CC");
  if (a < 0 || a > 100) a = 12;
  tmp = mul(a,2);
  tmp_0 = add(tmp,84);
  tmp_1 = div(tmp_0,2);
  a = sub(tmp_1,a);
  __retres = ! (a == b);
  return __retres;
}


