/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int main(int x)
 {
   int __retres;
   pc_label_sequence(1,1UL,1,2,"24",0);
   pc_label_sequence(1,1UL,2,2,"24",0);
   pc_label_sequence_condition(0,"25");
   int a = x - x;
   pc_label_sequence(1,2UL,1,2,"25",0);
   pc_label_sequence(1,2UL,2,2,"25",0);
   pc_label_sequence_condition(0,"26");
   int b = (a - a) * a;
   pc_label_sequence(1,3UL,1,2,"26",0);
   pc_label_sequence(1,3UL,2,2,"26",0);
   __retres = b * b + a * a;
   return __retres;
 }


