/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

struct coord {
    int x ;
    int y ;
};
int f(int x, int y)
{
  int __retres;
  struct coord test;
  pc_label_sequence(1,1UL,1,2,"25",0);
  pc_label_sequence(1,2UL,1,2,"26",0);
  pc_label_sequence(1,1UL,2,2,"25",0);
  pc_label_sequence_condition(0,"34");
  test.x = x;
  pc_label_sequence(1,3UL,1,2,"34",0);
  pc_label_sequence(1,2UL,2,2,"26",0);
  pc_label_sequence_condition(0,"35");
  test.y = y;
  pc_label_sequence(1,4UL,1,2,"35",0);
  pc_label_sequence(1,3UL,2,2,"34",0);
  pc_label_sequence(1,4UL,2,2,"35",0);
  __retres = test.x + test.y;
  return __retres;
}


