/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

void g(int x)
 {
   return;
 }

int j(void)
{
  int __retres;
  __retres = 1;
  return __retres;
}

void f(void)
{
  int x;
  pc_label_sequence_condition(0,"27");
  x = 0;
  pc_label_sequence(1,1UL,1,2,"27",0);
  pc_label_sequence(1,3UL,1,2,"27",0);
  while (1) {
    pc_label_sequence(1,1UL,2,2,"27",0);
    pc_label_sequence(1,2UL,2,2,"27",0);
    if (! (x < 10)) break;
    pc_label_sequence(1,3UL,2,2,"27",0);
    pc_label_sequence(1,4UL,2,2,"27",0);
    g(x);
    g(x);
    pc_label_sequence_condition(0,"27");
    x ++;
    pc_label_sequence(1,2UL,1,2,"27",0);
    pc_label_sequence(1,4UL,1,2,"27",0);
  }
  return;
}


