/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

void donothing(void)
 {
   return;
 }

int main(int i)
{
  int __retres;
  while (1) pc_label(1,1,"ELO");
  while (1) {
    pc_label(1,2,"ELO");
    donothing();
  }
  while (1) {
    pc_label(1,3,"ELO");
    if (! (i < 10)) break;
  }
  while (1) {
    if (i < 10) pc_label(1,4,"ELO"); else break;
    donothing();
  }
  while (1) {
    int tmp;
    pc_label(1,5,"ELO");
    tmp = i;
    i ++;
    ;
    if (! tmp) break;
  }
  while (1) {
    int tmp_0;
    tmp_0 = i;
    i ++;
    ;
    if (tmp_0) pc_label(1,6,"ELO"); else break;
    donothing();
  }
  while (1) pc_label(1,7,"ELO");
  while (1) {
    pc_label(1,8,"ELO");
    donothing();
  }
  while (1) {
    pc_label(1,9,"ELO");
    if (! (i < 10)) break;
  }
  while (1) {
    pc_label(1,10,"ELO");
    donothing();
    if (! (i < 10)) break;
  }
  while (1) {
    int tmp_1;
    pc_label(1,11,"ELO");
    tmp_1 = i;
    i ++;
    ;
    if (! tmp_1) break;
  }
  while (1) {
    int tmp_2;
    pc_label(1,12,"ELO");
    donothing();
    tmp_2 = i;
    i ++;
    ;
    if (! tmp_2) break;
  }
  __retres = 0;
  return __retres;
}


