/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

int main(int a, int b, int c)
 {
   int __retres;
   pc_label(a && b,1,"NCC");
   pc_label(a && ! b,2,"NCC");
   pc_label(! a && b,3,"NCC");
   pc_label(! a && ! b,4,"NCC");
   pc_label(a && c,5,"NCC");
   pc_label(a && ! c,6,"NCC");
   pc_label(! a && c,7,"NCC");
   pc_label(! a && ! c,8,"NCC");
   pc_label(b && c,9,"NCC");
   pc_label(b && ! c,10,"NCC");
   pc_label(! b && c,11,"NCC");
   pc_label(! b && ! c,12,"NCC");
   if ((a && b) || c) {
     __retres = 0;
     goto return_label;
   }
   __retres = 1;
   return_label: return __retres;
 }


