/* Generated by Frama-C LTest */


#ifndef pc_label
#define pc_label(...) do{}while(0)
#endif
#ifndef pc_label_bindings
#define pc_label_bindings(...) do{}while(0)
#endif
#ifndef pc_label_sequence
#define pc_label_sequence(...) do{}while(0)
#endif
#ifndef pc_label_sequence_condition
#define pc_label_sequence_condition(...) do{}while(0)
#endif

void donothing(void)
 {
   return;
 }

int main(int i)
{
  int __retres;
  pc_label_sequence(1,1UL,1,2,"80",0);
  while (1) pc_label_sequence_condition(0,"80");
  pc_label_sequence(1,1UL,2,2,"80",0);
  pc_label_sequence(1,2UL,1,2,"83",0);
  while (1) {
    pc_label_sequence_condition(0,"83");
    donothing();
  }
  pc_label_sequence(1,2UL,2,2,"83",0);
  pc_label_sequence(1,3UL,1,2,"85",0);
  while (1) {
    pc_label_sequence_condition(0,"85");
    if (! (i < 10)) break;
  }
  pc_label_sequence(1,3UL,2,2,"85",0);
  pc_label_sequence(1,4UL,1,2,"90",0);
  while (1) {
    if (i < 10) pc_label_sequence_condition(0,"90"); else break;
    donothing();
  }
  pc_label_sequence(1,4UL,2,2,"90",0);
  pc_label_sequence(1,5UL,1,2,"95",0);
  while (1) {
    int tmp;
    pc_label_sequence_condition(0,"95");
    tmp = i;
    i ++;
    ;
    if (! tmp) break;
  }
  pc_label_sequence(1,5UL,2,2,"95",0);
  pc_label_sequence(1,6UL,1,2,"103",0);
  while (1) {
    int tmp_0;
    tmp_0 = i;
    i ++;
    ;
    if (tmp_0) pc_label_sequence_condition(0,"103"); else break;
    donothing();
  }
  pc_label_sequence(1,6UL,2,2,"103",0);
  pc_label_sequence(1,7UL,1,2,"111",0);
  while (1) pc_label_sequence_condition(0,"111");
  pc_label_sequence(1,7UL,2,2,"111",0);
  pc_label_sequence(1,8UL,1,2,"113",0);
  while (1) {
    pc_label_sequence_condition(0,"113");
    donothing();
  }
  pc_label_sequence(1,8UL,2,2,"113",0);
  pc_label_sequence(1,9UL,1,2,"115",0);
  while (1) {
    pc_label_sequence_condition(0,"115");
    if (! (i < 10)) break;
  }
  pc_label_sequence(1,9UL,2,2,"115",0);
  pc_label_sequence(1,10UL,1,2,"121",0);
  while (1) {
    pc_label_sequence_condition(0,"121");
    donothing();
    if (! (i < 10)) break;
  }
  pc_label_sequence(1,10UL,2,2,"121",0);
  pc_label_sequence(1,11UL,1,2,"127",0);
  while (1) {
    int tmp_1;
    pc_label_sequence_condition(0,"127");
    tmp_1 = i;
    i ++;
    ;
    if (! tmp_1) break;
  }
  pc_label_sequence(1,11UL,2,2,"127",0);
  pc_label_sequence(1,12UL,1,2,"136",0);
  while (1) {
    int tmp_2;
    pc_label_sequence_condition(0,"136");
    donothing();
    tmp_2 = i;
    i ++;
    ;
    if (! tmp_2) break;
  }
  pc_label_sequence(1,12UL,2,2,"136",0);
  __retres = 0;
  return __retres;
}


